- name: Create Cloudbear directory
  file:
    path: "{{ wkdr_path }}"
    state: directory
    mode: '0755'

- name: Deploy docker-compose.yml
  template: 
    src: docker-compose.yml.j2
    dest: "{{ wkdr_path/file_installer }}"
    
- name: Start CloudBeaver using Docker Compose
  command: docker-compose up -d
  args:
    chdir: "{{ wkdr_path }}"
  
- name: Enable UFW
  ufw:
    state: enabled
    policy: deny

- name: Allow 8978/tcp
  ufw:
    rule: allow
    port: 1433
    proto: tcp 
