- name: Check if Docker CA certificate already exists
  stat:
    path: "{{ dest_folder_path }}/ca.crt"
  register: cert_stat

- name: Create Working directory
  file:
    path: "{{ dest_folder_path }}"
    state: directory
    mode: "0750"

- name: copy docker certificate
  copy:
    src: "{{ source_file_path }}"
    dest: "{{ dest_folder_path }}/ca.crt"
    owner: root
    group: root
    mode: '0644'
  when: not cert_stat.stat.exists
  notify: Restart Docker