version: '3.8'

services:
  artifactory-jfrog:
    image: releases-docker.jfrog.io/jfrog/artifactory-oss:7.77.5
    container_name: artifactory-jfrog
    restart: unless-stopped
    volumes:
      - /tools/jfrog/data/:/var/opt/jfrog/artifactory
    ports:
      - "8081:8081"
      - "8082:8082"